Update image-build.yml

diff --git a/.github/workflows/image-build.yml b/.github/workflows/image-build.yml
--- a/.github/workflows/image-build.yml
+++ b/.github/workflows/image-build.yml
@@ -63,26 +63,26 @@ jobs:
       with:
         version: 1.8.6
 
-    # - name: Build Custom GCP Image with Packer
-    #   id: packer_build
-    #   run: |
-    #     cd packer-dir
-    #     packer init .
-    #     packer_output=$(packer build -var 'artifact_path=${{ github.workspace }}/target/assignment1-1.0.0.jar' -var 'project_id=${{ secrets.GCP_PROJECT_ID }}' -var 'zone=${{ secrets.GCP_ZONE }}' . ) 
-    #     echo "$packer_output"
-    #     if echo "$packer_output" | grep -q 'A disk image was created'; then
-    #       IMAGE_ID=$(echo "$packer_output" | grep 'A disk image was created' | awk -F': ' '{print $NF}')
-    #       echo "Image ID: $IMAGE_ID"
-    #       echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
-    #     else
-    #       echo "Packer build failed or image ID was not found."
-    #       exit 1
-    #     fi
-    #   shell: bash
-    #   env:
-    #     GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
-    #     GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
-    #     GCP_ZONE: ${{ secrets.GCP_ZONE }}
+    - name: Build Custom GCP Image with Packer
+      id: packer_build
+      run: |
+        cd packer-dir
+        packer init .
+        packer_output=$(packer build -var 'artifact_path=${{ github.workspace }}/target/assignment1-1.0.0.jar' -var 'project_id=${{ secrets.GCP_PROJECT_ID }}' -var 'zone=${{ secrets.GCP_ZONE }}' . ) 
+        echo "$packer_output"
+        if echo "$packer_output" | grep -q 'A disk image was created'; then
+          IMAGE_ID=$(echo "$packer_output" | grep 'A disk image was created' | awk -F': ' '{print $NF}')
+          echo "Image ID: $IMAGE_ID"
+          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
+        else
+          echo "Packer build failed or image ID was not found."
+          exit 1
+        fi
+      shell: bash
+      env:
+        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
+        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
+        GCP_ZONE: ${{ secrets.GCP_ZONE }}
 
     - name: Authenticate to Google Cloud with service account
       uses: google-github-actions/auth@v0.4.0
