Update packer.yml

diff --git a/.github/workflows/packer.yml b/.github/workflows/packer.yml
--- a/.github/workflows/packer.yml
+++ b/.github/workflows/packer.yml
@@ -24,16 +24,16 @@ jobs:
         working-directory: packer-dir
         run: packer init .
 
-      - name: Run packer fmt
+      - name: Run packer fmt and check for unformatted files
         working-directory: packer-dir
         run: |
-          packer fmt -check -recursive . || true # Prevent immediate exit
-          fmt_exit_code=$?
-          echo "packer fmt -check exit code: $fmt_exit_code"
-          if [ $fmt_exit_code -ne 0 ]; then
-            echo "Packer template formatting check failed!"
+          # Format Packer files
+          packer fmt -recursive .
+          # Check if any files were modified by the formatting
+          git diff --exit-code . || {
+            echo "::error::Packer template formatting has modified files, indicating they were not properly formatted."
             exit 1
-          fi
+          }
 
 
       - name: Validate Packer Template with Variables
